# Generated by Django 5.0.1 on 2024-04-02 07:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', ckeditor.fields.RichTextField()),
                ('conclusion', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
