# Generated by Django 5.0.1 on 2024-04-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads')),
                ('facebook_link', models.CharField(max_length=1000)),
                ('twitter_link', models.CharField(max_length=1000)),
                ('instagram_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
